name: Fetch Pinned Repositories

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch pinned repositories
        run: |
          curl -H "Authorization: Bearer ${{ secrets.TOKEN_PAT }}" \
               -H "Content-Type: application/json" \
               -X POST -d '{ "query": "{ user(login: \"BUZZKILL1549\") { pinnedItems(first: 6, types: REPOSITORY) { nodes { name description url stargazerCount forkCount } } } }" }' \
               https://api.github.com/graphql > pinned_repos.json

      - name: Show file content (debugging)
        run: cat pinned_repos.json

      - name: Commit and push if changed
      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pinned_repos.json
          git commit -m "Updated pinned repositories" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
